package agent;

import org.objectweb.asm.ClassVisitor;

/**
 * Created by kyel on 3/11/2018.
 */

import org.objectweb.asm.*;
import static org.objectweb.asm.Opcodes.*;
import java.lang.reflect.Method;

class MethodAdapter extends MethodVisitor implements Opcodes {

    public MethodAdapter(final MethodVisitor mv) {
        super(ASM5, mv);
    }

    @Override
    public void visitMethodInsn(int opcode, String owner, String name, String desc, boolean itf) {
        /* System.err.println("CALL" + name); */
        System.out.println("Opcode: "+opcode+" Owner: "+ owner+ " Name: "+ name+ " Desc: "+desc);
        /* do call */
        mv.visitMethodInsn(opcode, owner, name, desc, itf);

        mv.visitFieldInsn(GETSTATIC, "java/lang/System", "err", "Ljava/io/PrintStream;");
        mv.visitLdcInsn("Generated by the java agent too");
        mv.visitMethodInsn(INVOKEVIRTUAL, "java/io/PrintStream", "println", "(Ljava/lang/String;)V", false);

    }
}